import { Video } from "../interface/movie";

export const videos: Video[] = [
  {
    title: "Leon",
    description: "Léon: The Professional",
    director: "Luc Besson",
    genre: "Action/Drama",
    image: "leon.jpg",
  },
  {
    title: "Se7en",
    description: "Se7en",
    director: "David Fincher",
    genre: "Crime/Thriller",
    image: "se7en.jpg",
  },
  {
    title: "Marriage Story",
    description: "Marriage Story",
    director: "Christopher Nolan",
    genre: "Drama/Romance",
    image: "marriage_story.jpg",
  },
  {
    title: "In the Mood for Love",
    description: "In the Mood for Love",
    director: "Wong Kar-wai",
    genre: "Romance/Drama",
    image: "in_the_mood_for_love.jpg",
  },
  {
    title: "Decision to Leave",
    description: "Decision to Leave",
    director: "Park Chan-wook",
    genre: "Drama/Romance",
    image: "decision_to_leave.jpg",
  },
  {
    title: "Interstellar",
    description: "Interstellar",
    director: "Christopher Nolan",
    favorite: true,
    genre: "Sci-Fi/Drama",
    image: "interstellar.jpg",
  },
  {
    title: "Inception",
    description: "Inception",
    director: "Christopher Nolan",
    genre: "Sci-Fi/Thriller",
    image: "inception.jpg",
  },
  {
    title: "Gladiator",
    description: "Gladiator",
    director: "Ridley Scott",
    genre: "Action/Drama",
    image: "gladiator.jpg",
  },
  {
    title: "The Matrix",
    description: "The Matrix",
    director: "The Wachowskis",
    genre: "Sci-Fi/Action",
    image: "the_matrix.jpg",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    description: "The Lord of the Rings: The Fellowship of the Ring",
    director: "Peter Jackson",
    genre: "Fantasy/Adventure",
    image: "the_lord_of_the_rings_the_fellowship_of_the_ring.jpg",
  },
  {
    title: "Begin Again",
    description: "Begin Again",
    director: "John Carney",
    genre: "Romance/Drama",
    image: "begin_again.jpg",
  },
  {
    title: "Hana and Alice",
    description: "Hana and Alice",
    director: "Shunji Iwai",
    favorite: true,
    genre: "Drama/Coming-of-Age",
    image: "hana_and_alice.jpg",
  },
  {
    title: "The Case of Hana & Alice",
    description: "The Case of Hana & Alice",
    director: "Shunji Iwai",
    genre: "Drama/Coming-of-Age",
    image: "the_case_of_hana_and_alice.jpg",
  },
  {
    title: "April Story",
    description: "April Story",
    director: "Shunji Iwai",
    favorite: true,
    genre: "Drama/Coming-of-Age",
    image: "april_story.jpg",
  },
  {
    title: "Love Letter",
    description: "Love Letter",
    director: "Shunji Iwai",
    favorite: true,
    genre: "Drama/Romance",
    image: "love_letter.jpg",
  },
  {
    title: "Spirited Away",
    description: "Spirited Away",
    director: "Hayao Miyazaki",
    favorite: true,
    genre: "Fantasy/Adventure",
    image: "spirited_away.jpg",
  },
  {
    title: "Akira",
    description: "Akira",
    director: "Katsuhiro Otomo",
    favorite: true,
    genre: "Sci-Fi/Action",
    image: "akira.jpg",
  },
  {
    title: "Good Will Hunting",
    description: "Good Will Hunting",
    director: "Gus Van Sant",
    genre: "Drama",
    image: "good_will_hunting.jpg",
  },
  {
    title: "Kung Fu Hustle",
    description: "Kung Fu Hustle",
    director: "Stephen Chow",
    genre: "Action/Comedy",
    image: "kung_fu_hustle.jpg",
  },
  {
    title: "Forrest Gump",
    description: "Forrest Gump",
    director: "Robert Zemeckis",
    genre: "Drama",
    image: "forrest_gump.jpg",
  },
];
