# Generated by Django 5.0.6 on 2024-09-20 07:39

import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BugManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='部落格的标题')),
                ('bug_detail', mdeditor.fields.MDTextField(verbose_name='部落格详情')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='previews/', verbose_name='部落格预览图片')),
                ('blog_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.blogtype', verbose_name='部落格类型')),
            ],
            options={
                'verbose_name': '部落格管理',
                'verbose_name_plural': '部落格管理',
            },
        ),
    ]
