# Generated by Django 5.0.6 on 2024-09-19 17:23

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=255)),
                ('bug_detail', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
