import { Book } from "../../interface/book";

export const mockBooks: Book[] = [
  {
    name: "接近無限透明的藍",
    author: "村上龍",
    favorites: false,
    imageUrl: "jie-jin-wu-xian-tou-ming-de-lan.jpg",
    genre: "小說",
  },
  {
    name: "69",
    author: "村上龍",
    favorites: false,
    imageUrl: "69.jpg",
    genre: "小說",
  },
  {
    name: "聽風的歌",
    author: "村上春樹",
    favorites: false,
    imageUrl: "ting-feng-de-ge.jpg",
    genre: "小說",
  },
  {
    name: "1973年的彈珠玩具",
    author: "村上春樹",
    favorites: false,
    imageUrl: "1973-nian-de-dan-zhu-wan-ju.jpg",
    genre: "小說",
  },
  {
    name: "尋羊冒險記",
    author: "村上春樹",
    favorites: false,
    imageUrl: "xun-yang-mao-xian-ji.jpg",
    genre: "小說",
  },
  {
    name: "世界末日與冷酷異境",
    author: "村上春樹",
    favorites: true,
    imageUrl: "shi-jie-mo-ri-yu-leng-ku-yi-jing.jpg",
    genre: "小說",
  },
  {
    name: "挪威的森林",
    author: "村上春樹",
    favorites: true,
    imageUrl: "nuo-wei-de-sen-lin.jpg",
    genre: "小說",
  },
  {
    name: "海邊的卡夫卡",
    author: "村上春樹",
    favorites: false,
    imageUrl: "hai-bian-de-ka-fu-ka.jpg",
    genre: "小說",
  },
  {
    name: "1Q84",
    author: "村上春樹",
    favorites: false,
    imageUrl: "1q84.jpg",
    genre: "小說",
  },
  {
    name: "沒有色彩的多崎作和他的巡禮之年",
    author: "村上春樹",
    favorites: true,
    imageUrl: "mei-you-se-cai-de-duo-qi-zuo-he-ta-de-xun-li-zhi-nian.jpg",
    genre: "小說",
  },
  {
    name: "神的孩子都在跳舞",
    author: "村上春樹",
    favorites: false,
    imageUrl: "shen-de-hai-zi-dou-zai-tiao-wu.jpg",
    genre: "小說",
  },
  {
    name: "第一人稱單數",
    author: "村上春樹",
    favorites: false,
    imageUrl: "di-yi-ren-cheng-dan-shu.jpg",
    genre: "小說",
  },
  {
    name: "甜美的來生",
    author: "村上春樹",
    favorites: true,
    imageUrl: "tian-mei-de-lai-sheng.jpg",
    genre: "小說",
  },
  {
    name: "王國",
    author: "村上春樹",
    favorites: false,
    imageUrl: "wang-guo-vol.jpg",
    genre: "小說",
  },
  {
    name: "盡頭的回憶",
    author: "村上春樹",
    favorites: true,
    imageUrl: "jin-tou-de-hui-yi.jpg",
    genre: "小說",
  },
  {
    name: "羽衣",
    author: "村上春樹",
    favorites: false,
    imageUrl: "yu-yi.jpg",
    genre: "小說",
  },
  {
    name: "虹",
    author: "村上春樹",
    favorites: false,
    imageUrl: "hong.jpg",
    genre: "小說",
  },
  {
    name: "不倫與南美",
    author: "村上春樹",
    favorites: false,
    imageUrl: "bu-lun-yu-nan-mei.jpg",
    genre: "小說",
  },
  {
    name: "甘露",
    author: "村上春樹",
    favorites: false,
    imageUrl: "gan-lu.jpg",
    genre: "小說",
  },
  {
    name: "鶇",
    author: "村上春樹",
    favorites: false,
    imageUrl: "dong.jpg",
    genre: "小說",
  },
  {
    name: "廚房",
    author: "吉本芭娜娜",
    favorites: true,
    imageUrl: "chu-fang.jpg",
    genre: "小說",
  },
  {
    name: "哀愁的預感",
    author: "吉本芭娜娜",
    favorites: false,
    imageUrl: "ai-chou-de-yu-gan.jpg",
    genre: "小說",
  },
  {
    name: "少年小樹之歌",
    author: "佛瑞斯特·卡特",
    favorites: false,
    imageUrl: "shao-nian-xiao-shu-zhi-ge.jpg",
    genre: "小說",
  },
  {
    name: "成為賈伯斯",
    author: "布倫特·施蘭德、瑞克·特策利",
    favorites: false,
    imageUrl: "cheng-wei-jia-bo-si.jpg",
    genre: "傳記",
  },
  {
    name: "傾城之戀",
    author: "張愛玲",
    favorites: false,
    imageUrl: "qing-cheng-zhi-lian.jpg",
    genre: "小說",
  },
  {
    name: "百年孤獨",
    author: "加夫列爾·加西亞·馬爾克斯",
    favorites: false,
    imageUrl: "bai-nian-gu-du.jpg",
    genre: "小說",
  },
  {
    name: "活著",
    author: "余華",
    favorites: false,
    imageUrl: "huo-zhe.jpg",
    genre: "小說",
  },
  {
    name: "三四郎",
    author: "夏目漱石",
    favorites: false,
    imageUrl: "san-si-lang.jpg",
    genre: "小說",
  },
  {
    name: "麥田捕手",
    author: "J·D·塞林格",
    favorites: false,
    imageUrl: "mai-tian-bu-shou.jpg",
    genre: "小說",
  },
  {
    name: "神鵰俠侶",
    author: "金庸",
    favorites: false,
    imageUrl: "shen-diao-xia-lv.jpg",
    genre: "武俠",
  },
  {
    name: "東機鐵塔",
    author: "村上龍",
    favorites: false,
    imageUrl: "dong-ji-tie-ta.jpg",
    genre: "小說",
  },
  {
    name: "盛夏之死",
    author: "遠藤周作",
    favorites: false,
    imageUrl: "sheng-xia-zhi-si.jpg",
    genre: "小說",
  },
  {
    name: "大亨小傳",
    author: "F·斯科特·菲茨傑拉德",
    favorites: false,
    imageUrl: "da-heng-xiao-chuan.jpg",
    genre: "小說",
  },
];
