# Generated by Django 5.0.6 on 2024-09-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcalgo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='封面圖片'),
        ),
    ]
