# Generated by Django 5.0.6 on 2024-09-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcalgo', '0002_remove_post_photos_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
