# Generated by Django 5.0.6 on 2024-09-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcalgo', '0003_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
