# Generated by Django 4.2.7 on 2024-05-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_solardevicedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solardevicedata',
            name='device_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='solardevicedata',
            name='electricity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solardevicedata',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='solardevicedata',
            name='people_count',
            field=models.IntegerField(default=0),
        ),
    ]
