# Generated by Django 4.2.7 on 2024-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_solardevicedata_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solardevicedata',
            name='location',
            field=models.CharField(default='建功高科大', max_length=50),
        ),
    ]
