# Generated by Django 5.0.6 on 2024-06-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0005_solardevicedata_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArduinoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.IntegerField(unique=True)),
                ("brightness", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
